version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./src/backend/config.json:/app/backend/config.json
      - ./src/uploads:/app/uploads
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always
