version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    network_mode: "host"  # <--- Hinzufügen!
    volumes:
      - ./src/backend/config.json:/app/backend/config.json
      - ./src/uploads:/app/uploads
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    network_mode: "host"  # <--- Hinzufügen!
    depends_on:
      - backend
    restart: always
