const sshService = require('../services/SSHService');
const path = require('path');
const fs = require('fs');

class MinecraftController {
    async sendCommand(req, res) {
        const { command, screenName = 'minecraft' } = req.body;
        if (!command) return res.status(400).json({ error: 'Command required' });

        try {
            const cmd = `screen -S ${screenName} -p 0 -X stuff "${command}\\n"`;
            await sshService.exec(cmd);
            res.json({ success: true });
        } catch (err) {
            res.status(500).json({ error: err.message });
        }
    }

    async getProperties(req, res) {
        const { path: serverPath } = req.query;
        if (!serverPath) return res.status(400).json({ error: 'No server path provided' });

        try {
            if (!sshService.connected) {
                return res.status(500).json({ error: 'SSH not connected. Please connect first in the dashboard.' });
            }

            const cleanPath = serverPath.replace(/\/+$/, '');
            const filePath = `${cleanPath}/server.properties`;

            console.log(`[Properties] loading path: ${filePath}`);

            const content = await sshService.exec(`cat "${filePath}"`).catch(e => {
                throw new Error(`Could not read server.properties. Make sure the file exists at: ${filePath}`);
            });

            const rawProps = {};
            if (content) {
                // Support both CRLF and LF
                content.split(/\r?\n/).forEach(line => {
                    const trimmed = line.trim();
                    if (trimmed && !trimmed.startsWith('#') && trimmed.indexOf('=') > 0) {
                        const idx = trimmed.indexOf('=');
                        const key = trimmed.substring(0, idx).trim();
                        const val = trimmed.substring(idx + 1).trim();
                        rawProps[key] = val;
                    }
                });
            }

            // Metadata for rich UI components
            const metadata = {
                'difficulty': { type: 'enum', options: ['peaceful', 'easy', 'normal', 'hard'], desc: 'The overall difficulty of the server.' },
                'gamemode': { type: 'enum', options: ['survival', 'creative', 'adventure', 'spectator'], desc: 'The default game mode for new players.' },
                'level-type': { type: 'enum', options: ['minecraft:normal', 'minecraft:flat', 'minecraft:large_biomes', 'minecraft:amplified', 'minecraft:single_biome_surface'], desc: 'The world generation algorithm.' },
                'pvp': { type: 'boolean', desc: 'Allows players to damage each other.' },
                'spawn-monsters': { type: 'boolean', desc: 'Whether monsters will spawn naturally.' },
                'spawn-animals': { type: 'boolean', desc: 'Whether animals will spawn naturally.' },
                'spawn-npcs': { type: 'boolean', desc: 'Whether Villagers will spawn.' },
                'white-list': { type: 'boolean', desc: 'If enabled, only whitelisted players can join.' },
                'online-mode': { type: 'boolean', desc: 'Authenticates players against Mojang servers.' },
                'hardcore': { type: 'boolean', desc: 'World is deleted and players banned on death.' },
                'allow-flight': { type: 'boolean', desc: 'Allows players to use flight mods.' },
                'allow-nether': { type: 'boolean', desc: 'Allows players to travel to the Nether.' },
                'enable-command-block': { type: 'boolean', desc: 'Enables command blocks.' },
                'max-players': { type: 'number', min: 1, max: 9999, desc: 'Maximum concurrent player limit.' },
                'server-port': { type: 'number', min: 1, max: 65535, desc: 'The network port for connections.' },
                'view-distance': { type: 'number', min: 2, max: 32, desc: 'Chunks sent to the player.' },
                'simulation-distance': { type: 'number', min: 2, max: 32, desc: 'Distance for ticking entities/blocks.' },
                'motd': { type: 'string', desc: 'The Message of the Day shown in server lists.' },
                'level-name': { type: 'string', desc: 'The name of the world folder.' }
            };

            res.json({ values: rawProps, metadata });
        } catch (err) {
            console.error('[Properties] ERROR:', err.message);
            res.status(500).json({ error: err.message });
        }
    }

    async saveProperties(req, res) {
        const { path: serverPath, properties } = req.body;
        if (!serverPath || !properties) return res.status(400).json({ error: 'Data required' });

        try {
            const filePath = `${serverPath.replace(/\/+$/, '')}/server.properties`;
            let content = "# Generated by Minecraft SSH Manager\n";
            content += `# ${new Date().toLocaleString()}\n`;

            for (const [key, value] of Object.entries(properties)) {
                content += `${key}=${value}\n`;
            }

            const escapedContent = content.replace(/"/g, '\\"').replace(/`/g, '\\`').replace(/\$/g, '\\$');
            await sshService.exec(`printf "%b" "${escapedContent}" > "${filePath}"`);

            res.json({ success: true });
        } catch (err) {
            res.status(500).json({ error: err.message });
        }
    }

    async controlServer(req, res) {
        const { action, serverPath } = req.body;

        try {
            if (!sshService.connected) {
                return res.status(500).json({ error: 'SSH not connected' });
            }

            // Load config to get custom scripts
            const configPath = path.join(__dirname, '..', '..', 'config.json');
            let config = { startScript: './start.sh', stopScript: 'stop', screenName: 'minecraft' };
            if (fs.existsSync(configPath)) {
                config = { ...config, ...JSON.parse(fs.readFileSync(configPath)) };
            }

            const activePath = serverPath || config.path;
            const screen = config.screenName || 'minecraft';

            if (action === 'start') {
                const script = config.startScript || 'java -jar server.jar';
                const isDefault = !config.startScript;

                // Path verification
                try {
                    await sshService.exec(`test -d "${activePath}"`);
                } catch (e) {
                    throw new Error(`Directory not found: ${activePath}`);
                }

                if (isDefault) {
                    console.log(`Starting default server via screen [${screen}] at ${activePath}`);
                    // Default behavior: screen for interactivity
                    await sshService.exec(`cd "${activePath}" && screen -dmS ${screen} ${script}`);
                } else {
                    console.log(`Executing direct start via pipe: ${script} at ${activePath}`);
                    // Direct execution with pipe support
                    const pipe = `${activePath}/.mc_pipe`;
                    const startCmd = `
                        cd "${activePath}" && \
                        rm -f ${pipe} && \
                        mkfifo ${pipe} && \
                        (tail -f ${pipe} | ${script} >> logs/latest.log 2>&1 &)
                    `.replace(/\s+/g, ' ').trim();
                    await sshService.exec(startCmd);
                }
            } else if (action === 'stop') {
                try {
                    console.log(`Stopping server ${screen}...`);
                    const stopCmd = config.stopScript || 'stop';

                    if (config.startScript) {
                        // Direct mode: use pipe
                        await sshService.exec(`echo "${stopCmd}" > "${activePath}/.mc_pipe"`);
                    } else {
                        // Screen mode
                        await sshService.exec(`screen -S ${screen} -p 0 -X stuff "${stopCmd}\\n"`);
                    }
                } catch (e) {
                    if (e.message && e.message.includes('No socket match') && !config.startScript) {
                        console.log('Server already stopped (no screen session).');
                    } else {
                        throw e;
                    }
                }
            } else if (action === 'restart') {
                try {
                    await sshService.exec(`screen -S ${screen} -p 0 -X stuff "stop\\r"`);
                } catch (e) { }

                setTimeout(async () => {
                    const script = config.startScript || './run.sh';
                    await sshService.exec(`cd ${activePath} && screen -dmS ${screen} ${script}`);
                }, 5000);
            } else if (action === 'kill') {
                await sshService.exec(`screen -S ${screen} -X quit`);
            } else if (action === 'reload') {
                await sshService.exec(`screen -S ${screen} -p 0 -X stuff "reload confirm\\r"`);
            }

            res.json({ success: true });
        } catch (err) {
            console.error('Control Error:', err.message);
            res.status(500).json({ error: err.message });
        }
    }

    async getPlayers(req, res) {
        try {
            // This is primarily handled via socket now, but kept for legacy
            res.json([]);
        } catch (err) {
            res.status(500).json({ error: err.message });
        }
    }
}

module.exports = new MinecraftController();
