const sshService = require('../services/SSHService');

class MinecraftController {
    async sendCommand(req, res) {
        const { command, screenName = 'minecraft' } = req.body;
        if (!command) return res.status(400).json({ error: 'Command required' });

        try {
            const cmd = `screen -S ${screenName} -p 0 -X stuff "${command}\\r"`;
            await sshService.exec(cmd);
            res.json({ success: true });
        } catch (err) {
            res.status(500).json({ error: err.message });
        }
    }

    async getProperties(req, res) {
        const { path: serverPath } = req.query;
        if (!serverPath) return res.status(400).json({ error: 'No server path provided' });

        try {
            if (!sshService.connected) {
                return res.status(500).json({ error: 'SSH not connected. Please connect first in the dashboard.' });
            }

            const cleanPath = serverPath.replace(/\/+$/, '');
            const filePath = `${cleanPath}/server.properties`;

            console.log(`[Properties] loading path: ${filePath}`);

            const content = await sshService.exec(`cat "${filePath}"`).catch(e => {
                throw new Error(`Could not read server.properties. Make sure the file exists at: ${filePath}`);
            });

            const rawProps = {};
            if (content) {
                // Support both CRLF and LF
                content.split(/\r?\n/).forEach(line => {
                    const trimmed = line.trim();
                    if (trimmed && !trimmed.startsWith('#') && trimmed.indexOf('=') > 0) {
                        const idx = trimmed.indexOf('=');
                        const key = trimmed.substring(0, idx).trim();
                        const val = trimmed.substring(idx + 1).trim();
                        rawProps[key] = val;
                    }
                });
            }

            // Metadata for rich UI components
            const metadata = {
                'difficulty': { type: 'enum', options: ['peaceful', 'easy', 'normal', 'hard'], desc: 'The overall difficulty of the server.' },
                'gamemode': { type: 'enum', options: ['survival', 'creative', 'adventure', 'spectator'], desc: 'The default game mode for new players.' },
                'level-type': { type: 'enum', options: ['minecraft:normal', 'minecraft:flat', 'minecraft:large_biomes', 'minecraft:amplified', 'minecraft:single_biome_surface'], desc: 'The world generation algorithm.' },
                'pvp': { type: 'boolean', desc: 'Allows players to damage each other.' },
                'spawn-monsters': { type: 'boolean', desc: 'Whether monsters will spawn naturally.' },
                'spawn-animals': { type: 'boolean', desc: 'Whether animals will spawn naturally.' },
                'spawn-npcs': { type: 'boolean', desc: 'Whether Villagers will spawn.' },
                'white-list': { type: 'boolean', desc: 'If enabled, only whitelisted players can join.' },
                'online-mode': { type: 'boolean', desc: 'Authenticates players against Mojang servers.' },
                'hardcore': { type: 'boolean', desc: 'World is deleted and players banned on death.' },
                'allow-flight': { type: 'boolean', desc: 'Allows players to use flight mods.' },
                'allow-nether': { type: 'boolean', desc: 'Allows players to travel to the Nether.' },
                'enable-command-block': { type: 'boolean', desc: 'Enables command blocks.' },
                'max-players': { type: 'number', min: 1, max: 9999, desc: 'Maximum concurrent player limit.' },
                'server-port': { type: 'number', min: 1, max: 65535, desc: 'The network port for connections.' },
                'view-distance': { type: 'number', min: 2, max: 32, desc: 'Chunks sent to the player.' },
                'simulation-distance': { type: 'number', min: 2, max: 32, desc: 'Distance for ticking entities/blocks.' },
                'motd': { type: 'string', desc: 'The Message of the Day shown in server lists.' },
                'level-name': { type: 'string', desc: 'The name of the world folder.' }
            };

            res.json({ values: rawProps, metadata });
        } catch (err) {
            console.error('[Properties] ERROR:', err.message);
            res.status(500).json({ error: err.message });
        }
    }

    async saveProperties(req, res) {
        const { path: serverPath, properties } = req.body;
        if (!serverPath || !properties) return res.status(400).json({ error: 'Data required' });

        try {
            const filePath = `${serverPath.replace(/\/+$/, '')}/server.properties`;
            let content = "# Generated by Minecraft SSH Manager\n";
            content += `# ${new Date().toLocaleString()}\n`;

            for (const [key, value] of Object.entries(properties)) {
                content += `${key}=${value}\n`;
            }

            const escapedContent = content.replace(/"/g, '\\"').replace(/`/g, '\\`').replace(/\$/g, '\\$');
            await sshService.exec(`printf "%b" "${escapedContent}" > "${filePath}"`);

            res.json({ success: true });
        } catch (err) {
            res.status(500).json({ error: err.message });
        }
    }

    async controlServer(req, res) {
        const { action, path: serverPath, screenName = 'minecraft' } = req.body;
        try {
            if (action === 'start') {
                await sshService.exec(`cd ${serverPath} && screen -dmS ${screenName} ./start.sh`);
            } else if (action === 'stop') {
                await sshService.exec(`screen -S ${screenName} -p 0 -X stuff "stop^M"`);
            } else if (action === 'restart') {
                await sshService.exec(`screen -S ${screenName} -p 0 -X stuff "stop^M"`);
                setTimeout(async () => {
                    await sshService.exec(`cd ${serverPath} && screen -dmS ${screenName} ./start.sh`);
                }, 5000);
            }
            res.json({ success: true });
        } catch (err) {
            res.status(500).json({ error: err.message });
        }
    }

    async getPlayers(req, res) {
        try {
            // This is primarily handled via socket now, but kept for legacy
            res.json([]);
        } catch (err) {
            res.status(500).json({ error: err.message });
        }
    }
}

module.exports = new MinecraftController();
